image: node:6.3.0

cache:
  paths:
  - node_modules/

test:
    script:
        - npm install
        - npm test

e2e-test:
    script:
        - npm install
        - npm run e2e

coverage:
    script:
        - npm install
        - npm run coverage