image: node:6.3.0

cache:
  paths:
  - node_modules/

before_script:
    - apt-get update -qq && apt-get install -y -qq libgtk2.0-0 libxtst6 libxss1 libgconf-2-4

test:
    script:
        - npm install
        - npm test

coverage:
    script:
        - npm install
        - npm run coverage